### PR TITLE
feat: outdated browser informational screen

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

when IE, older Chrome/Safari/Firefox connect to uPortal, uPortal will display information page suggesting the user upgrades to a evergreen browser.
built on http://outdatedbrowser.com/en

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by jgribonvald** [comment]
A big :+1: for a such feature !
I see that you've applied my suggestion ;)
One thing: maybe you could add this portlet to the guest layout, I'm doing like that to aknowledge the user before access that he doesn't use a well supported browser (more it could help on some authentication protocol, old browsers/OS doesn't support last security protocols).
After I've applied something similar (before seeing this tool) on my side to have a better control of what isn't considered: https://github.com/GIP-RECIA/uPortal-start/commit/2f939918fc3a306d467af358a75513103c8b68db (without data as externalized)
But take mine as an example, yourth should be better ;)

**Comment by ChristianMurphy** [comment]
> One thing: maybe you could add this portlet to the guest layout, I'm doing like that to aknowledge the user before access that he doesn't use a well supported browser (more it could help on some authentication protocol, old browsers/OS doesn't support last security protocols).

Will do

> An automatic i18n would be appreciated, but inside a CMS portlet it would be difficult.

I'll look into that

> I should test it

please do, the more testers the better!

**Comment by cousquer** [comment]
> 
> 
> > One thing: maybe you could add this portlet to the guest layout, I'm doing like that to aknowledge the user before access that he doesn't use a well supported browser (more it could help on some authentication protocol, old browsers/OS doesn't support last security protocols).
> 
> Will do
> 
> > An automatic i18n would be appreciated, but inside a CMS portlet it would be difficult.
> 
> I'll look into that
> 
> > I should test it
> 
> please do, the more testers the better!

je serai là ausi

**Comment by jgribonvald** [comment]
This is working ! tested with an IE11 setted as IE9.

But **I've found a problem**, you have a button asking to user to change his browser, and it's an external link on an "unknown" website ! so now I'm shared, what to do ?

**Comment by ChristianMurphy** [comment]
> This is working ! tested with an IE11 setted as IE9.

Excellent!

> so now I'm shared, what to do ?

Hover over the different browsers and click download for one or more?

> Also I should test more as I can't apply the fr.html test

Strange, does http://outdatedbrowser.com/fr work okay?

**Comment by cousquer** [comment]
> > One thing: maybe you could add this portlet to the guest layout, I'm doing like that to aknowledge the user before access that he doesn't use a well supported browser (more it could help on some authentication protocol, old browsers/OS doesn't support last security protocols).
> 
> 
> > An automatic i18n would be appreciated, but inside a CMS portlet it would be difficult.
> 
> I’m against this feature. Sorry 😐 @jgribonvald 🙏
>
> my concerns are here:
> from raushma (TC39) this tweet 
> https://mobile.twitter.com/rauschma/status/1091058510358564865
>
> and from Melanie Mitchell (Portland University ) in NY Times 
> https://www.nytimes.com/2018/11/05/opinion/artificial-intelligence-machine-learning.html
> 
> > I should test it
> 
> please do, the more testers the better!

Is this loaded on a mobile device ? Because it seems to adress only desktops devices not mobiles devices.

**Comment by cousquer** [comment]
Will test if the warning is keyboard accessible tomorrow 2019-02-01
And match WCAG 2.0 AA
Please do not merge before

**Comment by ChristianMurphy** [comment]
> > An automatic i18n would be appreciated, but inside a CMS portlet it would be difficult.
>
> I'll look into that

See: https://github.com/burocratik/outdated-browser/issues/304

**Comment by cousquer** [comment]
> > > An automatic i18n would be appreciated, but inside a CMS portlet it would be difficult.
> > 
> > 
> > I'll look into that
> 
> See: [burocratik/outdated-browser#304](https://github.com/burocratik/outdated-browser/issues/304)

I have look at that, it is a little "burocratik" 😄 
I prefer this point  of vue: 
https://w3c.github.io/bp-i18n-specdev/#lang_negotiation
Much more conforms with what I was saying at Apereo in 2017 _(but that's a personal insight)_
https://cousquer.github.io/apereo2017/#/8/6

> Don't assume language dictates location and location dictates the language, Let the user choose: when the user change his local language, the *portal* / portlet is displayed in this language according to the user's customization...

**Comment by jgribonvald** [comment]
> > > > An automatic i18n would be appreciated, but inside a CMS portlet it would be difficult.
> > > 
> > > 
> > > I'll look into that
> > 
> > 
> > See: [burocratik/outdated-browser#304](https://github.com/burocratik/outdated-browser/issues/304)
> 
> I have look at that, it is a little "burocratik" smile
> I prefer this point of vue:
> https://w3c.github.io/bp-i18n-specdev/#lang_negotiation
> Much more conforms with what I was saying at Apereo in 2017 _(but that's a personal insight)_
> https://cousquer.github.io/apereo2017/#/8/6
> 
> > Don't assume language dictates location and location dictates the language, Let the user choose: when the user change his local language, the _portal_ / portlet is displayed in this language according to the user's customization...

That's what I tried to say, the problem here is that the message will be always English due to this configuration:
`languagePath: '/resource-server/webjars/outdatedbrowser/lang/en.html`
Their should be something that set a user adapted/prefered language !

>
On the other side @ChristianMurphy you didn't get my point: about the link inside the message shown, the user have a button shown which redirect to an outside and non institutional website ! That's the problem, it's not a "trusted" website !

**Pull request closed without merging**
