### PR TITLE
Issue #16: Setup continuous integration

### LINKED ISSUE #16: Setup continuous integration
Add Travis CI and AppVeyor CI to automatically test code.

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [x] tests are included

##### Description of change

Resolves #16
Includes #15

Adds Travis CI as linux ci.
Adds AppVeyor as windows ci.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
:construction: :construction_worker_man: Build output:
https://travis-ci.org/ChristianMurphy/uPortal-start/builds/247366931
https://ci.appveyor.com/project/ChristianMurphy/uportal-start/build/1.0.2

:notebook: This should be squash merged after #15 has been applied.

**Comment by drewwills** [comment]
Thanks -- we need this addition.

I don't see any of the typical "build passing" notices near the merge button... do we need someone to enable travis or appveyor somehow?

**Comment by ChristianMurphy** [comment]
>  don't see any of the typical "build passing" notices near the merge button... do we need someone to enable travis or appveyor somehow?

yes
Travis CI needs to be switched on here: https://travis-ci.org/profile/Jasig
AppVeyor needs to be switched on here: https://ci.appveyor.com/projects/new

**Comment by drewwills** [comment]
Done.

**Comment by ChristianMurphy** [comment]
Reapplied changes to force build

**Comment by ChristianMurphy** [comment]
Builds passing :white_check_mark: 
Adding Travis CI badge [Linux Build Status](https://travis-ci.org/Jasig/uPortal-start)
AppVeyor hides their badges behind hashes, @drewwills could grab the snippet from https://ci.appveyor.com/project/drewwills/uportal-start/settings/badges and add it to the README?

**Pull request merged**
