### PR TITLE
Update to uPortalVersion 5.0.2

### PR DESCRIPTION
**Pull request by drewwills**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

Released today!

https://github.com/Jasig/uPortal/releases/tag/v5.0.2

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
@drewwills if you have a chance could you include a link in the description to the v5.0.2 release notes here, and tick both the checkmarks?
Thanks! :bow:

**Comment by ChristianMurphy** [comment]
:construction_worker_man: :no_entry: :checkered_flag: AppVeyor is flagging

> <{https://source.jasig.org/schemas/uportal/io/portlet-definition}portlet-definition version="4.3"> entities failed to import.

Extended log

> [ant:java] Exception in thread "main" java.lang.RuntimeException: data-import from data/quickstart 
> matching null failed
> [ant:java] 	at org.apereo.portal.shell.PortalShellBuildHelperImpl.importFromDirectoryUsingPattern(PortalShellBuildHelperImpl.java:353)
> [ant:java] 	at org.apereo.portal.shell.PortalShellBuildHelperImpl.dataImport(PortalShellBuildHelperImpl.java:312)
> [ant:java] 	at org.apereo.portal.shell.PortalShellBuildHelper$dataImport$3.call(Unknown Source)
> [ant:java] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
> [ant:java] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
> [ant:java] 	at dataInit.run(dataInit.groovy:52)
> [ant:java] 	at groovy.lang.GroovyShell.runScriptOrMainOrTestOrRunnable(GroovyShell.java:263)
> [ant:java] 	at groovy.lang.GroovyShell.run(GroovyShell.java:227)
> [ant:java] 	at org.apereo.portal.shell.PortalShell.main(PortalShell.java:74)
> [ant:java] Caused by: java.lang.RuntimeException: 1 <{https://source.jasig.org/schemas/uportal/io/portlet-definition}portlet-definition version="4.3"> entities failed to import.
> [ant:java] 
> [ant:java] 	Per entity exception logs and a full report can be found in C:\projects\uportal-start\overlays\uPortal\build\data-import-reports
> [ant:java] 
> [ant:java] 	at org.apereo.portal.io.xml.JaxbPortalDataHandlerService.importDataDirectory(JaxbPortalDataHandlerService.java:649)
> [ant:java] 	at org.apereo.portal.shell.PortalShellBuildHelperImpl.importFromDirectoryUsingPattern(PortalShellBuildHelperImpl.java:346)
> [ant:java] 	... 8 more
> :overlays:uPortal:dataInit FAILED
> :overlays:uPortal:dataInit (Thread[Daemon worker,5,main]) completed. Took 39.281 secs.
> FAILURE: Build failed with an exception.
> * Where:
> Build file 'C:\projects\uportal-start\overlays\uPortal\build.gradle' line: 217
> * What went wrong:
> Execution failed for task ':overlays:uPortal:dataInit'.
> > Java returned: 1

source: https://ci.appveyor.com/project/drewwills/uportal-start/build/1.0.192#L8003

**Comment by drewwills** [comment]
@ChristianMurphy -- afaik this is the same issue we've been seeing for days.

How do I see these?...

```
Per entity exception logs and a full report can be found in C:\projects\uportal-start\overlays\uPortal\build\data-import-reports
```

**Comment by ChristianMurphy** [comment]
> How do I see these?

``` batch
type C:\projects\uportal-start\overlays\uPortal\build\data-import-reports
```

restart the build.
contents will then be reported to the build logs.

**Pull request merged**
