### PR TITLE
Implements Gradle task 'deployPortletApp' loosely matching the Ant task of the same name in uP4

### PR DESCRIPTION
**Pull request by drewwills**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [x] documentation is changed or added

##### Description of change

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
Maven local?

This task is a tool for deploying a portlet `war` file without overlaying it.

**Comment by ChristianMurphy** [comment]
Right, do we want to support that in uPortal 5?
Having everything routed through maven seems to work well.

**Comment by drewwills** [comment]
I think this is one of those items -- like `SimpleSecurityContext` -- that's probably not suited to a server deployment, but handy to have in a local dev environment.

When you're early-stage prototyping a new portlet, it's nice to be able to see it in operation without going through the fuss of bundling it.

**Comment by ChristianMurphy** [comment]
-0
I see the motivation behind it.
However it feels like a step backwards, uPortal 5 has made massive investment in closing the gap local dev and production versions.
re-adding functionality intended for local use only widens that gap.

**Pull request merged**
