### PR TITLE
Added support for custom Gradle tasks

### PR DESCRIPTION
**Pull request by jonathanmtran**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

This patch adds support for custom Gradle tasks (such as #156) that are not (yet) a part of uPortal-start. 

I'm trying to keep our modifications to our fork uPortal-start limited as much as possible and I think this will add some flexibility without having to worry about resolving merge conflicts in the future.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by jonathanmtran** [comment]
An example is #156 (Added a task to reinstall the appropriate shared libraries for uPortal)

**Comment by drewwills** [comment]
Out of curiosity, what kind of custom tasks are you adding?

I'm also curious, but generally I think this enhancement is a good idea.

**Comment by jonathanmtran** [comment]
Here's another use case from the uportal-dev mailing list
https://groups.google.com/a/apereo.org/forum/#!topic/uportal-dev/xEr1RTMx4iM

Another use case that came to mind while doing a production deploy is to "fork" the `tomcatTar` task such that it excludes folders such as `ROOT`, `manager`, and friends

**Comment by ChristianMurphy** [comment]
Not a blocker just a thought. :thinking: :thought_balloon: 
uPortal as a whole has been moving toward configuration and convention over code.
Will this somewhat side step that ideal and goal, by encouraging writing custom gradle tasks instead of enhancing the existing ones with new configuration options?

**Comment by drewwills** [comment]
Will this somewhat side step that ideal and goal, by encouraging writing custom
    gradle tasks instead of enhancing the existing ones with new configuration options?

I don't think it's a problem _per se_.

The new capability is merely a tool;  it can be used well or misused.  I think the potential for undermining our other efforts depends a great deal on how the capability is used.

**Pull request merged**
