### PR TITLE
chore(gradle): update bundled tomcat 8 version to latest

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

Updates version to latest V8.0 series

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
@ChristianMurphy -- did you do a comparison, and visually confirm that the files in `etc/tomcat` -- which are overlaid in the build process -- match up with the versions of the same files in the updated Tomcat dependency?

I don't think it's ever safe to skip that step.

**Comment by ChristianMurphy** [comment]
> did you do a comparison, and visually confirm that the files in etc/tomcat -- which are overlaid in the build process

I did

> match up with the versions of the same files in the updated Tomcat dependency?

They do

> I don't think it's ever safe to skip that step.

Feel free to add this to the uPortal docs.

**Comment by bjagg** [comment]
uPortal works with Tomcat 8.5. Why not upgrade to 8.5.23?

**Comment by drewwills** [comment]
I'm good with that @bjagg.

**Comment by ChristianMurphy** [comment]
closing in favor of #64

**Pull request closed without merging**
