### PR TITLE
Can now filter for database properties

### PR DESCRIPTION
**Pull request by bpowell**
##### Checklist

-   [x ] the [individual contributor license agreement][] is signed

##### Description of change

Now allows users to filter the database connections to their liking. 

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by bpowell** [comment]
@drewwills  I need this merged in to be able to create docker images. Otherwise the docker image cannot connect to a database.

**Comment by ChristianMurphy** [comment]
Would the solution used in Jasig/uPortal/pull/853 work here?

cc @andrewstuart

**Comment by bpowell** [comment]
@ChristianMurphy no it would not. That is for the old uPortal. We talked at the conference about changing that PR to be more inline with Apereo and not tied to Andrew's stuff. Also @drewwills wanted a gradle process to produce a docker image. I have most of that working right now locally.

**Comment by drewwills** [comment]
We certainly can consider including this stuff as long as we have filters, but (in the not too distant future) we were hoping to get away from cooking settings into the artifacts at build time altogether.

We're also hoping to be 100% Gradle-based.

**Comment by ChristianMurphy** [comment]
> no it would not. That is for the old uPortal. We talked at the conference about changing that PR to be more inline with Apereo and not tied to Andrew's stuff.

Fair enough, I am not privy to that conversation, but more generic support for containerization does seem like a good direction to go.

> Also @drewwills wanted a gradle process to produce a docker image. I have most of that working right now locally.

Right, that is my understanding as well.

Do you have any thoughts on how this would be Gradle-ized?
Would you be interested in helping Gradle-ize this and other tasks?

**Comment by drewwills** [comment]
The thought ATM is that all deployment-specific configuration settings will be handled in a `.properties` file external to the uPortal webapp.  It would be similar to the `overrides.properties` approach (but may benefit from some revisions).  There may also be some Gradle-based tooling to help you create such a file, if there's value in that.

**Comment by andrewstuart** [comment]
I'd recommend heavily towards just using a standard spring [PropertySourcesPlaceholderConfigurer](https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/context/support/PropertySourcesPlaceholderConfigurer.html) for externalizing configuration and getting rid of all possible build-time filtering.

The benefits with containerization are that you can include properties as YAML, `foo.bar=baz`-style, or even by setting environment variables like `FOO_BAR=baz`. It really ends up giving you the most flexibility with containerized solutions as to how you want to go about specifying your runtime configuration.

Moving towards a more standard Spring runtime-configurable application will also help enable cool solutions like Spring Cloud Configuration.

Anyway, just my two cents :-)

**Comment by drewwills** [comment]
Most configs already go through the `PropertySourcesPlaceholderConfigurer`;  the ones that don't will need to be refactored to go through it... at least if they need to be adjusted per-deployment.

**Comment by bpowell** [comment]
I can try my hand at making this use OS environmental variables and push up commits for that. As for turning the entire thing into a gradle based build, I'm not sure how much I can help, but I can get the ball rolling for the docker part.

**Comment by ChristianMurphy** [comment]
> I can try my hand at making this use OS environmental variables and push up commits for that.

:+1: 

> I'm not sure how much I can help

There are plenty of bite sized tasks, moving tasks that are currently in ant and maven over to gradle.
Where whatever time you can contribute helps move the effort forward. :smile: 
Jasig/uPortal/pull/890 and Jasig/uPortal/pull/889 are two excellent examples. :star2: 

> I can get the ball rolling for the docker part.

**Comment by bpowell** [comment]
@drewwills @andrewstuart when we are talking about removing filtering, are we talking about removing it completely? Like we no longer need filters/x.properties. All XML files will have the environmental variables directly instead of using *.properties file (that will pull from OS environmental variables)? Or do we want to go with a half way step for right now? Like leave the filters/*.properties files and have them link to the OS environment variables?

**Comment by andrewstuart** [comment]
I would personally say completely eliminated. There is a slight issue with the web.xml and such files where they don't get processed by spring, but my experience has been that even those can be replaced by `-D` defining properties during startup. Docker's entrypoint facility makes it really easy to do that and even extend that to using environment variables with defaults. The downside of that approach is that it can potentially complicate regular tomcat usage by requiring properties to be set.

Also, re: encrypted properties, I know it's popular and looks good to users to allow encrypted properties, but my experience has been that it's really dangerous because you might be hiding really really bad passwords behind an encrypted layer that makes people forget that they're using `admin:password` in production. This exact thing just happened on a project and nobody noticed because the encrypted properties obscured the very poor passwords.

So I guess just a word of caution about making encrypted properties files a first-class uPortal feature. There are much more secure ways these days of providing secure access to secrets that can enforce security policies and rotation (e.g. Vault) that encrypted static files just can't provide.

**Comment by bpowell** [comment]
If we completely eliminate properties then all portlets will have to be updated to use OS environmental variables as well. We would still have to allow portlets to filter for older versions of uPortal (4.3.x series). Documentation will need to be very clear about how that works for using a portlet in uPortal 5 verse uPortal 4.

**Comment by drewwills** [comment]
We may want to use OS environment variables in some specific/important cases, but I think most of it --
 at least in a basic install -- will be in an external (not in Tomcat/uPortal/) .properties file.

**Comment by andrewstuart** [comment]
Just to clarify, if it is set up to use Spring properties and the `@Value` annotation, and if you use the default spring property config, or make sure you enable the environment provider, then you get both environment variables and properties files for free. Spring can/will examine both (plus a few other sources like `--command.line.params=foo` and potentially  `-Ddefined.property=foo` IIRC), and is smart enough to use the proper conventions when searching e.g. system environment variables.

So for example, given `@Value("foo.bar") private String fooBar = "";` or in an XML config file, the placeholder `${foo.bar}`, an application can set the value of `fooBar` by:

- including a properties file with `foo.bar=baz`
- setting the environment variable `FOO_BAR=baz`
- passing the cli argument/param of `--foo.bar=baz`
- (maybe) defining the system property `foo.bar` a la `-Dfoo.bar=baz`

The out-of-the-box Spring config for this is very flexible and it can also be configured to the project needs. So I would

**Comment by drewwills** [comment]
@andrewstuart Is there a good documentation source for this system?  (I'd like to include it by reference.)

**Comment by andrewstuart** [comment]
This may be the best: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html. It's technically for Spring Boot, but I believe that just means that the documented behavior is how Spring Boot configures the Spring PropertySource-related utilities. All the configuration behaviors should hopefully be attainable without requiring Spring Boot.

**Comment by bpowell** [comment]
@drewwills @ChristianMurphy one of you said both and the other said just OS env vars. Can we come to an agreement on this?

**Comment by ChristianMurphy** [comment]
@bpowell Sorry for the confusion, both.

**Comment by ChristianMurphy** [comment]
Hey @bpowell maven has been completely removed from `uPortal-start`. (#21)
Since this PR is maven based, I'm going to close it out.

It will still be really great to have these be more configurable. :+1: 
Hope to see a Spring based PR soon. :smiley:

**Pull request closed without merging**
