### PR TITLE
Update uPortalVersion to 5.3.0

### PR DESCRIPTION
**Pull request by drewwills**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

There is currently a [pull request in uPortal](https://github.com/Jasig/uPortal/pull/1356) to remove the _template user_ feature.

**Rationale:** Template users were (in 2.0) for populating the groups & layout of new portal users, but both of those functions are better handled now by something else -- PAGS & DLM (fragments), respectively.  We have _actively discouraged_ the use of template users for a decade or more.

If it merges, it will be in the next minor version (5.3.0).

When 5.3.0 releases with that change, these changes will be necessary.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by jgribonvald** [comment]
One question, maybe idiot, is there a need to remove theses datas from already initiated database from previous version when upgrading to a new uPortal version ?
To be clear I never seen something on how to migrate a database from an older to a new version.

**Comment by drewwills** [comment]
@jgribonvald --

    One question, maybe idiot, is there a need to remove theses datas from already
    initiated database from previous version when upgrading to a new uPortal version ?
    To be clear I never seen something on how to migrate a database from an older to
    a new version.

A few approaches may be possible, but there is only one _supported_ approach:

  - Full export
  - New, empty database schema
  - Full import

We know this approach works.  If it doesn't, we're committed to making it work.  We are not committed to making any other approach work.

Anyone who wants to use a different approach is free to do so, but should not expect that the community will feel obligated to spring into action if anything goes wrong.

**Comment by jgribonvald** [comment]
@drewwills thanks for your response.
But is it possible to run the portal without a database cleaning when you come from a 5.2 version ? In my mind I don't see any problem on as you removed the code that used theses datas...

**Comment by drewwills** [comment]
@jgribonvald et al.,

I don't think there's any issue if this data is already in the database;  it's only an issue (AFAIK) if you try to import this data.

**Comment by ChristianMurphy** [comment]
@drewwills what else remains to merge this?

**Comment by drewwills** [comment]
@ChristianMurphy I don't think anything remains in the PR, but we should probably communicate effectively around 5.3.0.  I can dig into that this afternoon.

**Pull request merged**
