### PR TITLE
UP-4918:  Some support for leveraging these changes (UP-4918) in uPortal-start

### PR DESCRIPTION
**Pull request by drewwills**
https://issues.jasig.org/browse/UP-4918

##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [x] documentation is changed or added

##### Description of change

[UP-4918](https://issues.jasig.org/browse/UP-4918) has been merged into `uPortal`.  This PR includes some minor tweaks to help you take advantage of those updates from within `uPortal-start`.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
It's likely that the CI won't pass at this point, since `5.0.0-M2` was sent to sonatype only minutes ago.

**Comment by ChristianMurphy** [comment]
Travis CI builds appear to be on track to passing :white_check_mark: 

:warning: Closing and reopening PR to retrigger AppVeyor CI :recycle: :construction:

**Comment by ChristianMurphy** [comment]
@drewwills CI is failing with:

``` log
[ant:java] Caused by: java.sql.SQLSyntaxErrorException: object name already exists: UP_PORTLET_DEF in statement [create table UP_PORTLET_DEF (PORTLET_DEF_ID bigint not null, ACTION_TIMEOUT integer, PORTLET_DESC varchar(255), ENTITY_VERSION bigint, EVENT_TIMEOUT integer, PORTLET_FNAME varchar(255) not null, PORTLET_NAME varchar(128) not null, PORTLET_FRAMEWORK boolean not null, PORTLET_APPLICATION_NAME varchar(255) not null, PORTLET_WEBAPP_NAME varchar(255), AVG_RATING double, RENDER_TIMEOUT integer, RESOURCE_TIMEOUT integer, PORTLET_TIMEOUT integer not null, PORTLET_TITLE varchar(128) not null, AVG_RATING_USER_COUNT bigint, PORTLET_PREFS_ID bigint not null, PORTLET_TYPE_ID integer not null, primary key (PORTLET_DEF_ID))]
```

Clearing build cache and restarting build again to see if that resolves error. :construction: :recycle:

**Comment by ChristianMurphy** [comment]
Travis CI is fully passing now :white_check_mark: 
It may be worth sending out a note that the schema for `UP_PORTLET_DEF` has changed and people should be prepared to migrate :bird: 

@drewwills I don't have permissions to reset the build cache on AppVeyor. :no_entry: 
Could you add me to the project, or login to appveyor in chrome, open the js console and paste.

``` js
$.ajax({
    url: 'https://ci.appveyor.com/api/projects/drewwills/uportal-start/buildcache',
    type: 'DELETE'
})
```

Thanks :bowing_man:

**Pull request merged**
