### PR TITLE
feat: Providing an advanced manager and monitor for Apache Tomcat

### PR DESCRIPTION
**Pull request by jgribonvald**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]
-   [ ] tests are included
-   [ ] documentation is changed or added
-   [ ] [message properties][] have been updated with new phrases
-   [ ] view conforms with [WCAG 2.0 AA][]

##### Description of change

This PR intend to provide an advanced manager and monitor for Apache Tomcat.

Easy to test: 
* deploy 
* go on http://localhost:8080/psi-probe/ 
* enter login: `manager ` and password: `CHANGEIT`
* and navigate !

To set a new password you should go on etc/tomcat/conf/tomcat-users.xml and set a new one or configure tomcat user access on your own.

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/.github/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by jgribonvald** [comment]
I can write and provide a documentation, but let me know if there is an interest before to work on documentation.

**Comment by ChristianMurphy** [comment]
screenshot_2018-10-18 probe - announcements - application summary
screenshot_2018-10-18 probe - installed applications
screenshot_2018-10-18 probe - running threads

**Comment by asgrant** [comment]
We've had experience adding this into our production environment. I would at this point advice against it, unless someone can solve a problem (or it is no longer an issue with the newer versions of psi-probe). Some systems we had at OU that require TLS termination at the box caused problems with psi-probe to work properly. We only had luck with psi-probe when it was behind a reverse proxy (i.e. behind NGINX or our F5 and those front-ends were terminating TLS).

We had this in our deployment process with uP4 for a few years, once we got New Relic, we yanked it from all our environments (Banner, uPortal, Identity) at OU.

**Comment by asgrant** [comment]
Also to add, if the final decision is to not include it, I would suggest putting this into uPortal documentation and promoting in the uportal-user group. It was extremely valuable when we had it working in our environment and couldn't afford a solution like New Relic.

**Comment by jgribonvald** [comment]
I never had a problem with it but but we are behind frontal, also it's not recommended to expose it to the web, and only accessing from a local non used connector and from local server name is suffisant. We are behind a frontal configuration using ajp connector and it's not configured on the proxy :wink:

After like you say it could be only a documentation that tell how to deploy it - maybe watching at a property (like for swagger) to activate it !

This version is recent.

On an other side I changed the server.xml to set all context statically (I list all deployed services) and I set unpackWARs="false" autoDeploy="false" to avoid problems, it's more secure !

**Comment by jgribonvald** [comment]
After my PR could be closed, it's not the problem, at least I shown a solution.

**Comment by ChristianMurphy** [comment]
> GNU GPL v2

GPL is in Apache category X, meaning we should not include/enable this by default https://apache.org/legal/resolved.html#what-can-we-not-include-in-an-asf-project-category-x

Apache recommends

> Apache projects cannot distribute any such components within their releases. However, if the component is only needed for optional features, a project can provide the user with instructions on how to obtain and install the non-included work. Optional means that the component is not required for standard use of the product or for the product to achieve a desirable level of quality. The question to ask yourself in this situation is:
> * "Will the majority of users want to use my product without adding the optional components?"


https://apache.org/legal/resolved.html#optional

**Comment by drewwills** [comment]
I think -- at a minimum - documenting this setup could be useful.

**Comment by ChristianMurphy** [comment]
Hey @jgribonvald! Thanks for suggesting this feature! :bow:
The license not being compatible with Apache 2.0 is going to be a blocker for merging this. :stop_sign: 
A pull request documenting how PSI Probe can be used would be a license-compatible and welcome addition! :star2:

**Pull request closed without merging**
