### PR TITLE
chore:  update uPortal to 5.8.0

### PR DESCRIPTION
**Pull request by cbeach47**
### Checklist
-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change
Bumping up uPortal to the latest version

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
closes #371

**Comment by jonathanmtran** [comment]
We should take this opportunity to 
- default `encodeServiceUrl` to `false` such that uPortal works with the bundled CAS 
- add documentation in the relevant places talking about this

If someone doesn't beat me to the punch, I'll put this together (hopefully) this afternoon or tomorrow

**Comment by jonathanmtran** [comment]
Pull request #373 has the relevant modification such that `encodeServiceUrl` is set to `false`. Any modifications to better clarify the note are welcome.

**Comment by cbeach47** [comment]
Closing in favor of #373.

**Pull request closed without merging**
