### PR TITLE
build(gradle): allow generation of project files to intellij and eclipse

### PR DESCRIPTION
**Pull request by ChristianMurphy**
##### Checklist

-   [x] the [individual contributor license agreement][] is signed
-   [x] commit message follows [commit guidelines][]

##### Description of change

Make it easier to setup uPortal-start with Eclipse and Intellij

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

### CODE REVIEW

**Comment by drewwills** [comment]
I'd like to kick the tires of this change before merging.  I do have some concerns.

We definitely need to support the ability for different developers to configure their IDEs differently without either...

  - The plugin resetting their customizations;  or
  - Files in the repo showing up as deltas with `$ git status`

One example:  I have several clones of uPortal-start.  I name them differently in Idea (Project Settings) so I can tell which one I have open.

**Comment by ChristianMurphy** [comment]
> Files in the repo showing up as deltas with `$ git status`

All the generated files are already covered by the gitignore.

> The plugin resetting their customizations

This plugin is optional, `./gradle idea` and `./gradlew eclipse` have to be manually called.
If you want to have additional customizations you can.

**Comment by ChristianMurphy** [comment]
Also note that these plugins are already enabled for uPortal.
https://github.com/Jasig/uPortal/blob/6d98dbcfc9c22fdaef237d20228eff261689e20a/build.gradle#L43
https://github.com/Jasig/uPortal/blob/6d98dbcfc9c22fdaef237d20228eff261689e20a/build.gradle#L41

**Comment by drewwills** [comment]
> This plugin is optional, ./gradle idea and ./gradlew eclipse have to be manually called.

That works.  :+1:

**Pull request merged**
